version: '3'
services:
  carml:
    build: .
    ports:
    - 80:80
  zipkin:
    image: openzipkin/zipkin:1.29
    ports:
    - 9411:9411
  consul:
    image: consul
    ports:
    - 8500:8500
  caffe2:
    environment:
      - TRACER_ENDPOINTS='[zipkin:9411]'
      - REGISTRY_ENDPOINTS='[consul:8500]'
    links:
      - zipkin
      - consul
    image: carml/caffe-agent:amd64-cpu-latest
