version: '3.3'
services:
  carml:
    image: carml/web:amd64
    ports:
    - 8088:8088
    links:
    - zipkin
    - consul
    - caffe2
    depends_on:
    - zipkin
    - consul
    - caffe2
    environment:
    - PORT=8088
    - TRACER_ENDPOINTS=zipkin:9411
    - REGISTRY_ENDPOINTS=consul:8500
    entrypoint: carml web -d -v
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: ~/.carml_config.yml
      target: /root/.carml_config.yml
  zipkin:
    image: openzipkin/zipkin:1.29
    container_name: zipkin
    ports:
    - 9411:9411
  consul:
    image: consul
    container_name: consul
    ports:
    - 8500:8500
  # store:
  #   image: minio/minio
  #   container_name: store
  #   ports:
  #   - 9000:9000
  #   command: server /export
  #   environment:
  #   - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
  #   - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  #   volumes:
  #   - ~/data/store:/export
  #   - ~/data/store:/root/.minio
  caffe2:
    image: carml/caffe2-agent:amd64-cpu-latest
    container_name: caffe2
    links:
    - zipkin
    - consul
    entrypoint: caffe2-agent -d -v -l
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: ~/.carml_config.yml
      target: /root/.carml_config.yml
    environment:
    - PORT=9012
    - EXTERNAL_HOST=localhost
    - EXTERNAL_PORT=9012
    - TRACER_ENDPOINTS=zipkin:9411
    - REGISTRY_ENDPOINTS=consul:8500
    depends_on:
    - zipkin
    - consul
    ports:
    - 9012:9012
  # caffe:
  #   environment:
  #     - TRACER_ENDPOINTS=zipkin:9411
  #     - REGISTRY_ENDPOINTS=consul:8500
  #   links:
  #     - zipkin
  #     - consul
  #   image: carml/caffe-agent:amd64-cpu-latest
  #   command: -l
  #   volumes:
  #     - ~/.carml_config.yml:/root/.carml_config.yml
  # caffe:
  #   environment:
  #     - TRACER_ENDPOINTS=zipkin:9411
  #     - REGISTRY_ENDPOINTS=consul:8500
  #   links:
  #     - zipkin
  #     - consul
  #   image: carml/caffe-agent:amd64-cpu-latest
  #   command: -l
  #   volumes:
  #     - ~/.carml_config.yml:/root/.carml_config.yml
  # mxnet:
  #   environment:
  #     - TRACER_ENDPOINTS=zipkin:9411
  #     - REGISTRY_ENDPOINTS=consul:8500
  #   links:
  #     - zipkin
  #     - consul
  #   image: carml/mxnet-agent:amd64-cpu-latest
  #   command: -l
  #   volumes:
  #     - ~/.carml_config.yml:/root/.carml_config.yml
